fitball/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls import url, handler404, handler500, url, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitball_app.urls')),
]

urlpatterns += [
    url(r'media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }),
]

admin.site.site_header = 'Fitball Admin'

fitball_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'fitball'
urlpatterns = [
    path('', views.devices, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name="app/login.html"), name='login'),
    path('devices/', views.devices, name='devices'),
    path('connect-device/<str:id>/', views.connect_device, name='connect-device'),
    path('new-goal/<str:id>/', views.new_goal, name='new-goal'),
    path('connect-discord/', views.connect_discord_id, name='connect-discord'),
    path('new-competition/', views.new_competition, name='new-competition'),
    path('join-competition/<str:id>', views.join_competition, name='join-competition'),
    path('api/update-performance/', views.update_all_user_performance_data, name='api/update-performance'),
    path('api/update-user-performance/', views.update_user_performance_data, name='api/update-user-performance'),
    path('api/waitlist/', views.waitlist, name='api/waitlist'),
    path('api/update-competition/', views.update_competition_performance, name='api/update-competition'),
]

fitball_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Device(models.Model):
    device_name = models.CharField(max_length = 200)
    display_number = models.IntegerField(default = 0)
    logo = models.ImageField(blank = True, null = True, upload_to = "media/")
    active = models.BooleanField(default = False)
    def __str__(self):
        return self.device_name

class Connected_Device(models.Model):
    username = models.CharField(max_length = 200, default = '')
    password = models.CharField(max_length = 200, default = '')
    device_user_id = models.CharField(max_length = 200)
    device_access_token = models.CharField(max_length = 200)
    device = models.ForeignKey(Device, on_delete = models.CASCADE, null = True)
    user = models.ForeignKey(User, default = None, blank = True, null = True, on_delete = models.CASCADE)
    def __str__(self):
        return f'{self.user.username} // {self.device.device_name}'

class Goal(models.Model):
    user = models.ForeignKey(User, default = None, blank = True, null = True, on_delete = models.CASCADE)
    device = models.ForeignKey(Device, on_delete = models.CASCADE, null = True)
    goal_category = models.CharField(max_length = 200)
    clean_goal_metric = models.CharField(max_length = 200)
    device_goal_metric = models.CharField(max_length = 200)
    goal_value = models.FloatField(max_length = 200)
    goal_dollars = models.FloatField(max_length = 200)
    active = models.BooleanField(default = False)
    start_date = models.DateTimeField(blank = True, null = True)
    end_date = models.DateTimeField(blank = True, null = True)
    def __str__(self):
        return f'{self.user.username} // {self.goal_category} // {self.clean_goal_metric} // {self.goal_value}'

class Discord(models.Model):
    user = models.OneToOneField(User, default = None, null = True, on_delete = models.CASCADE)
    discord_username = models.CharField(max_length = 200)
    discord_id = models.CharField(max_length = 200)
    def __str__(self):
        return self.discord_username

class Competition(models.Model):
    name = models.CharField(max_length = 200)
    metric = models.CharField(max_length = 200)
    clean_metric = models.CharField(max_length = 200)
    metric_category = models.CharField(max_length = 200)
    format = models.CharField(max_length = 200)
    frequency = models.CharField(max_length = 200)
    goal_value = models.FloatField(default = 0)
    dollars = models.FloatField(default = 0)
    active = models.BooleanField(default = True)
    private = models.BooleanField(default = True)
    start_date = models.DateTimeField(blank = True, null = True)
    end_date = models.DateTimeField(blank = True, null = True)
    discord_channel_id = models.CharField(max_length = 200)
    users = models.ManyToManyField(User)
    device = models.ForeignKey(Device, on_delete = models.CASCADE, blank = True, null = True)
    def __str__(self):
        return f'{self.name} // {self.device} // {self.metric_category} // {self.metric} // {self.format}'

fitball_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .models import Device, Connected_Device, Goal, Discord, Competition
from rest_framework.views import APIView
from rest_framework.response import Response
from django.contrib.auth.models import User
from .forms import connect_device_form, new_goal_form, discord_form, new_competition_form
from django.utils import timezone
from rest_framework.authentication import SessionAuthentication, BasicAuthentication, TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
import urllib.parse
# Import methods from app
from app import (
    authenticate_user,
    fetch_device_metrics,
    fetch_all_device_metrics,
    user_goal_performance,
    fetch_user_performance,
    fetch_user_device_credentials,
    fetch_device_data,
    fetch_goal_data_from_device,
)
# Import methods from aws
from aws import (
  fetch_file_from_s3,
  post_file_to_s3,
)
# Import methods from discord_bot
from discord_bot import (
    fetch_user_id_from_username,
    fetch_dm_channel_id,
    send_message,
    create_new_channel,
)
# Import methods from views_methods
from views_methods import (
    check_device_credentials,
    check_discord_id,
    fetch_user_device,
    check_if_device_is_active,
    add_user_to_competition,
    join_competition_logic,
    determine_competition_winners,
    format_leaderboard_message,
)
# Import settings
from settings import (
  dt,
  relativedelta,
  json,
  os,
  np,
)

'''
Method: index

Summary: Index page
- If user has an account, log them in
- If user does not have an account, prompt them to connect a device
'''
def index(request):
    context = {}
    return render(request, 'app/index.html', context)

'''
Method: devices

Summary: Prompts the user to connect a wearable device
'''
def devices(request):
    devices = Device.objects.order_by('display_number')
    context = {'devices': devices}
    return render(request, 'app/devices.html', context)

'''
Method: connect_device

Summary: Allows the user to fill out a form to connect to the specified wearable device
'''
def connect_device(
    request,
    id,
):
    form = connect_device_form(id)
    devices = Device.objects.order_by('display_number')
    device = Device.objects.get(pk=id)
    device_logo = device.logo.url

    if request.method == 'POST':
        form = connect_device_form(id, request.POST)

        if form.is_valid():
            # Check to ensure that the user inputted valid credentials, then run the following code
            try:
                device_credentials_work = check_device_credentials(
                    device,
                    form,
                    request,
                )

                # Render success page
                if device_credentials_work:
                    return HttpResponseRedirect(f'/new-goal/{device.id}')

            # If the user inputted invalid credentials, prompt the user to try again
            except ValueError:
                error_message = f"We couldn't connect to your {device.device_name}, please enter your information again."
                return render(
                    request,
                    'app/connect_device_form.html',
                    {
                        'form': form,
                        'id': id,
                        'device': device,
                        'device_logo': device_logo,
                        'error_message': error_message,
                    }
                )

    else:
        form = connect_device_form(id)
    
    return render(
        request,
        'app/connect_device_form.html',
        {
            'form': form,
            'id': id,
            'device': device,
            'device_logo': device_logo,
        }
    )

'''
Method: new_goal

Summary: Allows the user to add a goal for a specific device
'''
def new_goal(
    request,
    id
):
    form = new_goal_form(id)
    devices = Device.objects.order_by('display_number')
    device = Device.objects.get(pk=id)
    device_logo = device.logo.url

    # Fetch the categories and metrics for the specified device
    connected_device = Connected_Device.objects.get(
        user = request.user,
        device = device,
    )
    user_credentials = {
        'device_user_id': connected_device.device_user_id,
        'device_access_token': connected_device.device_access_token,
    }
    categories_and_metrics = fetch_device_metrics(
        device.device_name,
        user_credentials,   
    )
    device_categories = categories_and_metrics['categories']
    device_metrics = categories_and_metrics['metrics']

    authentication_classes = (
        SessionAuthentication,
        BasicAuthentication,
        TokenAuthentication,
    )
    permission_classes = (IsAuthenticated,)

    if request.method == 'POST':
        form = new_goal_form(id, request.POST)

        if form.is_valid():
            # Check to ensure that the user inputted valid credentials, then run the following code
            try:
                # Get the content of the form
                form_data = form.save(commit = False)

                # Set the goal's start_date to right now
                form_data.start_date = timezone.now()

                # Set the goal's active state to active
                form_data.active = True

                # Set the goal's device to device
                form_data.device = device

                # Set the goal's user to the authenticated user
                form_data.user = request.user

                # Get the device_metric_name from the clean_metric_name
                device_metric_name = [
                    d['device_metric_name'] for d in device_metrics[form_data.goal_category] if d['clean_metric_name'] == form_data.clean_goal_metric
                ][0]
                form_data.device_goal_metric = device_metric_name

                # If the user is not new, and they have already connected to this device, then update
                # the data. Otherwise, create a new row
                goal_id = 0
                try:
                    existing_goal = Goal.objects.get(
                        user = request.user,
                        device = device,
                        goal_category = form_data.goal_category,
                        device_goal_metric = device_metric_name,
                    )
                    existing_goal.goal_value = form_data.goal_value
                    existing_goal.goal_dollars = form_data.goal_dollars
                    goal_id = existing_goal.id
                    existing_goal.save()

                except ObjectDoesNotExist:
                    goal_id = form_data.id
                    form_data.save()

                # Add goal to goals_db
                goals_db = fetch_file_from_s3(os.environ['goals_db'])
                new_row = [{
                    'user_id': request.user.id,
                    'device_id': device.id,
                    'goal_id': goal_id,
                    'user': request.user.username,
                    'device': device.device_name,
                    'goal_category': form_data.goal_category,
                    'clean_goal_metric': form_data.clean_goal_metric,
                    'device_goal_metric': device_metric_name,
                    'goal_value': form_data.goal_value,
                    'goal_dollars': form_data.goal_dollars,
                    'active': form_data.active,
                    'start_date': form_data.start_date,
                    'end_date': form_data.end_date,
                }]
                goals_db = goals_db.append(
                    new_row, ignore_index=True
                ).drop_duplicates(
                    subset = ['user', 'device', 'goal_category', 'device_goal_metric'],
                    keep = 'last',
                )
                post_file_to_s3(
                    goals_db,
                    'goals.csv',
                )

                # If the user has already connected their Discord ID, render the success page
                has_discord_id = Discord.objects.filter(
                    user = request.user
                ).count() > 0
                if has_discord_id:
                    context = {'device': device, 'device_logo': device_logo}
                    return render(request, 'app/new_goal_success.html', context)
                # If the user has not already connected their Discord ID, prompt them to enter their Discord ID
                else:
                    return HttpResponseRedirect('/connect-discord')

            # If the user inputted invalid credentials, prompt the user to try again
            except ValueError:
                error_message = f"We couldn't connect to your {device.device_name}, please enter your information again."
                return render(request, 'app/new_goal_form.html', {'form': form, 'id': id, 'device': device, 'device_logo': device_logo, 'error_message': error_message})

    else:
        form = new_goal_form(id)
  
    return render(
        request,
        'app/new_goal_form.html',
        {
            'form': form,
            'id': id,
            'device': device,
            'device_logo': device_logo,
            'device_categories': json.dumps(device_categories),
            'device_metrics': json.dumps(device_metrics),
        }
    )

'''
Method: connect_discord_id

Summary: Connects the user's Discord ID to their account
'''
def connect_discord_id(
    request,
):
    form = discord_form()

    authentication_classes = (
        SessionAuthentication,
        BasicAuthentication,
        TokenAuthentication,
    )
    permission_classes = (IsAuthenticated,)

    if request.method == 'POST':

fitball_app/templates/app/connect_device_form.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

<nav class="nav">
    <a class="nav_logo" href="/">
        <img class="fitball_logo" src="https://fitball.s3.us-east-2.amazonaws.com/Images/FitBot.png">
    </a>
</nav>

<div class = "body">
    {% if error_message %}
        <div class = "error_message">
            {{ error_message }}
        </div>
    {% endif %}
    {% if success_message %}
        <div class = "success_message">
            {{ success_message }}
        </div>
    {% endif %}
    <div class = "form">
        <img src="{% static 'app/images/'|add:device.device_name|add:'.png' %}">
        <span class = "form_header">Enter your {{ device }} credentials</span>
        <span class = "form_sub_header">
            We <span class = "yellow_background">never save</span> your login info or health data!
            Because of that, we'll <span class = "blue_background">need you to reconnect your {{device}}</span> every few days 😊
        </span>
        <form method="POST" class = "form_items" id="connect_device_form">
            {% csrf_token %}
            <input type="hidden" id="action" name="action" value="connect_device">
            <input type="hidden" id="device" name="device" value={{device}}>
            {{ form.as_p }}
            <button type="submit" class="button yellow form_button" onclick="checkCredentials()">Submit</button>
        </form>
    </div>
    </br>
    <a class = "form_sub_header" href="{% url 'fitball:devices' %}">Connect a different device</a>
</div>

<div id = "overlay" style="display:none">
    <span class = "header">
        Checking your {{ device }} credentials
    </span>
</div>

<script>
    function checkCredentials() {
      document.getElementById("overlay").style.display = "flex";
    }
</script>

{% endblock %}

fitball_app/templates/app/connect_device_success.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

<nav class="nav">
    <a class="nav_logo" href="/">
        <img class="fitball_logo" src="https://fitball.s3.us-east-2.amazonaws.com/Images/FitBot.png">
    </a>
</nav>

<div class = "body">
    <div class = "grid_master">
        <img src="{% static 'app/images/'|add:device.device_name|add:'.png' %}">
        <div class = "form_header"><strong>We successfully connected to your {{ device }}!</strong></div>
        <div class = "form_sub_header">Now, let's <a href = "{% url 'fitball:new-goal' device.id %}">set up a goal</a> for you to compete against.</div>
    </div>
</div>

{% endblock %}

fitball_app/templates/app/devices.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

<nav class="nav">
    <a class="nav_logo" href="/">
        <img class="fitball_logo" src="https://fitball.s3.us-east-2.amazonaws.com/Images/FitBot.png">
    </a>
</nav>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class = "body">
    <div class = "header">
        Connect a <span class = "green_text">fitness wearable</span>.
        </br>Set <span class = "blue_text">daily goals</span>.
        </br>Compete to <span class = "orange_text">win money</span>.
    </div>

    <div class = "grid">
    {% csrf_token %}
    {% for device in devices %}
        <div class = "grid_item">
            <div class = "grid_item_image">
                <img src="{% static 'app/images/'|add:device.device_name|add:'.png' %}">
            </div>
            {% if device.active == True %}
                    <a class = "button yellow" href="{% url 'fitball:connect-device' device.id %}">
                        Connect your {{device.device_name}}!
                    </a>
            {% else %}
                <a class = "button white" href="#" onclick="OpenComingSoonForm({{device.id}});" id="device_inactive_{{device.id}}">
                    Coming soon, get notified!
                </a>
                <div style="display:none" class="hidden_form" id="hidden_form_{{device.id}}">
                    <form id="contact_form" name="contact_form" data-name="Contact Form" method="post" class="hidden_form_flex">
                        {% csrf_token %}
                        <div class="w-embed">
                            <input type="hidden" id="device_{{device.id}}" name="device" value="{{device.device_name}}">
                        </div>
                        <div>
                            <input class="hidden_form_input" type="text" maxlength="256" name="name" data-name="name" placeholder="First Name" id="name_{{device.id}}" required="">
                        </div>
                        <div>
                            <input class="hidden_form_input" type="email" maxlength="256" name="email" data-name="email" placeholder="Email Address" id="email_{{device.id}}" required="">
                        </div>
                        <button class="button black" type="submit" onclick="SubmitForm({{device.id}})">Notify me!</button>
                    </form>
                </div>
                <a style="display:none" class="button green" id="success_message_{{device.id}}">
                    Thank you!
                </a>
                <a style="display:none" class="button orange" id="fail_message_{{device.id}}">
                    Oops! Something went wrong while submitting the form.
                </a>
            {% endif %}
        </div>
    {% endfor %}
    </div>
</div>  

<script>
    function OpenComingSoonForm(id){
        document.getElementById("hidden_form_" + id).style.display = 'block';
        document.getElementById("device_inactive_" + id).style.display = 'none';
    }
</script>
<script>
    function SubmitForm(id) {
        console.log('#hidden_form_' + id);
        const form = $('#hidden_form_' + id);
        form.on('submit', function(event){
            event.preventDefault();

            $.ajax({
                method: "POST",
                url: "/api/waitlist/",
                dataType: "json",
                data: {
                    "device": document.getElementById("device_" + id).value,
                    "name": document.getElementById("name_" + id).value,
                    "email": document.getElementById("email_" + id).value,
                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                },
                success : function(json) {
                    document.getElementById("success_message_" + id).style.display = 'block';
                    document.getElementById("hidden_form_" + id).style.display = 'none';
                },
                error: function(error_data){
                    console.log("Error")
                    console.log(error_data)
                    document.getElementById("fail_message_" + id).style.display = 'block';
                    document.getElementById("hidden_form_" + id).style.display = 'none';
                }
            });
        });
    }
</script>

{% endblock %}

fitball_app/templates/app/discord_form_success.html
{% extends 'app/base.html' %}

{% block content %}

<nav class="nav">
    <a class="nav_logo" href="/">
        <img class="fitball_logo" src="https://fitball.s3.us-east-2.amazonaws.com/Images/FitBot.png">
    </a>
</nav>

<div class = "body">
    <span class = "form_header">
        Awesome, we connected your Discord ID!
        </br>If you ever want to check your data, just message <span class = "yellow_background">!update</span> to FitBot 💪🤖
    </span>
    <span class = "form_sub_header">
        You should have just gotten a <span class = "blue_background">message from FitBot</span>
        </br>If you didn't get it, re-enter your username <a href="{% url 'fitball:connect-discord' %}">here</a>
    </span>
</div>

{% endblock %}

fitball_app/templates/app/new_competition_form.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

<nav class="nav">
    <a class="nav_logo" href="/">
        <img class="fitball_logo" src="https://fitball.s3.us-east-2.amazonaws.com/Images/FitBot.png">
    </a>
</nav>
</br>
<div class = "body">
    {% if error_message %}
        <div class = "error_message">
            {{ error_message }}
        </div>
    {% endif %}
    <div class = "form">
        <span class = "form_header">
            Let's set up a <span class = "yellow_background">new competition</span>! 💪
        </span>
        <form method="POST" class = "form_items" id="new_competition_form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button yellow form_button">Submit</button>
        </form>
    </div>
</div>
</br>

<script>
    {% block jquery %}

        // Fetch the categories and metrics values
        const categories_and_metrics = {{ categories_and_metrics|safe }};
        let device = '{{ default_device }}';
        let categories = categories_and_metrics[device]['categories'];
        let metrics = categories_and_metrics[device]['metrics'];

        // Populate the category drop down with that device's category options
        for (category of categories) {
            $('#id_metric_category').append($('<option/>', {
                class: "dropdown-item",
                text : category,
            }));
        }

        // Populate the metrics drop down with the metrics for that category
        // First, get the selected category
        const default_category = categories[0];
        // Then, populate the metrics for that category
        for (metric of metrics[default_category]) {
            $('#id_metric').append($('<option/>', {
                class: "dropdown-item",
                text : metric['clean_metric_name'],
            }));
        }

        // Populate the format drop down with the format options
        // First, define the format options
        const formats = [
            'Beat The Goal',
            'Winner Take All',
        ]
        // Then, populate the metrics for that category
        for (format of formats) {
            $('#id_format').append($('<option/>', {
                class: "dropdown-item",
                text : format,
            }));
        }

        // If the competition format value changes, and the value is not 'Beat The Goal',
        // remove the field and label. If the format value changes back to 'Beat The Goal',
        // add back the label and field
        $("#id_format").change(function() {
            const updated_format = $("#id_format").val();
            console.log(updated_format);

            if (updated_format !== 'Beat The Goal') {
                $("label[for='id_goal_value']").hide();
                document.getElementById('id_goal_value').style.display = 'none';
            } else {
                $("label[for='id_goal_value']").show();
                document.getElementById('id_goal_value').style.display = 'inline';
            }
        });
        
        // Populate the Dollar value with 1
        $('#id_dollars').val(1);

        // If the category changes, populate the metrics for that category
        $("#id_metric_category").change(function() {
            const updated_category = $("#id_metric_category").val();

            $('#id_metric').empty()
            for (metric of metrics[updated_category]) {
                $('#id_metric').append($('<option/>', {
                    class: "dropdown-item",
                    text : metric['clean_metric_name'],
                }));
            }
        });

        // If the device changes, change the categories and metrics values
        $("#id_device").change(function() {
            device = $("#id_device").val();
            categories = categories_and_metrics[device]['categories'];
            metrics = categories_and_metrics[device]['metrics'];

            // Define a default category for the device
            const updated_category = categories[0];
            // Update the metric values for that category
            $('#id_metric').empty()
            for (metric of metrics[updated_category]) {
                $('#id_metric').append($('<option/>', {
                    class: "dropdown-item",
                    text : metric['clean_metric_name'],
                }));
            }
        });

    {% endblock %}
</script>
        
{% endblock %}

fitball_app/templates/app/new_goal_form.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

<nav class="nav">
    <a class="nav_logo" href="/">
        <img class="fitball_logo" src="https://fitball.s3.us-east-2.amazonaws.com/Images/FitBot.png">
    </a>
</nav>
<div class = "body">
    {% if error_message %}
        <div class = "error_message">
            {{ error_message }}
        </div>
    {% endif %}
    <div class = "form">
        <img src="{% static 'app/images/'|add:device.device_name|add:'.png' %}">
        <span class = "form_header">
            We <span class = "yellow_background">successfully connected</span> to your {{ device }}! 🥳
        </br><span class = "blue_background">Add a goal</span> you'd like to hit each day 💪
        </span>
        <form method="POST" class = "form_items" id="new_goal_form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button yellow form_button">Submit</button>
        </form>
    </div>
</div>

<script>
    {% block jquery %}

        // Fetch the categories and metrics values
        const categories = {{ device_categories|safe }};
        const metrics = {{ device_metrics|safe }};

        // Populate the category drop down with that device's category options
        for (category of categories) {
            $('#id_goal_category').append($('<option/>', {
                class: "dropdown-item",
                text : category,
            }));
        }

        // Populate the metrics drop down with the metrics for that category
        // First, get the selected category
        const default_category = categories[0];
        // Then, populate the metrics for that category
        for (metric of metrics[default_category]) {
            $('#id_clean_goal_metric').append($('<option/>', {
                class: "dropdown-item",
                text : metric['clean_metric_name'],
            }));
        }

        // Populate the Goal Value with the user's average for that metric
        // First, get the default metric for the default category
        const default_metric = metrics[default_category][0];
        $('#id_goal_value').val(Math.round(default_metric.avg));

        // Populate the Dollar value with 1
        $('#id_goal_dollars').val(1);

        // If the category changes, populate the metrics for that category
        $("#id_goal_category").change(function() {
            const updated_category = $("#id_goal_category").val();

            $('#id_clean_goal_metric').empty()
            for (metric of metrics[updated_category]) {
                $('#id_clean_goal_metric').append($('<option/>', {
                    class: "dropdown-item",
                    text : metric['clean_metric_name'],
                }));
            }

            // Populate the Goal Value with the user's average for that metric
            // First, get the default metric for the default category
            const default_metric = metrics[updated_category][0];
            $('#id_goal_value').val(Math.round(default_metric.avg));
        });

        // If the metric changes, change the Goal Value
        $("#id_clean_goal_metric").change(function() {
            const updated_category = $("#id_goal_category").val();
            const updated_metric = $("#id_clean_goal_metric").val();

            // Populate the Goal Value with the user's average for that metric
            const category_metrics = metrics[updated_category];
            const selected_metric_object = category_metrics
                .filter(m => m.clean_metric_name === updated_metric)[0];
            $('#id_goal_value').val(Math.round(selected_metric_object.avg));
        });

    {% endblock %}
</script>
        
{% endblock %}

fitball_app/templates/app/new_goal_success.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

<nav class="nav">
    <a class="nav_logo" href="/">
        <img class="fitball_logo" src="https://fitball.s3.us-east-2.amazonaws.com/Images/FitBot.png">
    </a>
</nav>

<div class = "body">
    <img src="{% static 'app/images/'|add:device.device_name|add:'.png' %}">
    <span class = "form_header">
        Way to add a {{ device }} goal!
    </span>
    <span class = "form_sub_header">
        We'll <span class = "green_background">send you daily updates</span> on how you're performing against your goals and <span class = "blue_background">let you know if you need to reconnect your {{ device }}</span>.
        You can also <span class = "orange_background">see your results whenever you want</span> by <a href = "/connect-discord">joining the Fitball Discord</a>.
    </span>
    <div class = "form_sub_header">
        <a href = "{% url 'fitball:new-goal' device.id %}">
            Add another goal
        </a>
    </div>
</div>

{% endblock %}